In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 1.3 MB/s eta 0:00:009 kB/s eta 0:00:01
Requirement already satisfied: numpy>=1.26.0 in /home/priya/myenv/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/priya/myenv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/priya/myenv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 10.5 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

**Pandas** : Pandas ak python ni libraries che. Pandas data handal karva mate use thay che jeva k koi students na marks hoy to ema thi apde missing values ne remove kari sakhavi
             and duplicates values ne remove kari sakhavi. atle k data clean karva mate pandas use thay che. large data handle kari sakhavi. pandas ak excel jevi che pn excel ma
             small data handle thay and pandas ma large data handle thay. excel ma manually karvu pade jem k koi user ne manually video suggest karva impossible che and apde 
             pandas ma ak var model banavi atle automatic video suggest kare model automatic past behevior na through vidoe suggest kare ek example apu k apde koi cricket no
             joyo hoy to model bija sports na related video suggest kare. aa kam excel sheet kartu nathi. pandas ma 2 main structure che 1 sereies and 2 dataframe. Series ma 
             single column hoy.

**DataFrame** : DataFrame ak Table formate ma hoy che. Structure 2D ma hoy che multiple columns and row hoy che . DataFrame ak multiple columns no group hoy che. atle data ne 
                analysis kari sakhavi. jem k koi student na data ne handle karva che to data mathi top student find kari sakhiye , avgrage value find kari sakhavi. Ai/ML model
                use karti pela data ne clean karva pade. missing value ne handel karvu pade and model ne format ma handle karvu pade .
                row data -> DataFrame -> clean data -> ML model use kare.

In [9]:
import pandas as pd
data = {
    "name" : ["A","B","C"],
    "Marks" : [20,15,30]
}


df=pd.DataFrame(data)
print(df)

#   name  Marks
# 0    A     20
# 1    B     15
# 2    C     30

A=df.head()
print("Student data:",A)

# Student data:   name  Marks
# 0    A     20
# 1    B     15
# 2    C     30


#particular colums Select
df["Marks"]
# 0    20
# 1    15
# 2    30
# Name: Marks, dtype: int64




#Filter 
b = df[df["Marks"] >15]
print(b)
#   name  Marks
# 0    A     20
# 2    C     30

  name  Marks
0    A     20
1    B     15
2    C     30
Student data:   name  Marks
0    A     20
1    B     15
2    C     30
  name  Marks
0    A     20
2    C     30

**CSV file** : csv file data store karva mate simple formate che. jem database mysql ma data store thay am csv file ma data store kare che. jem k koi online shopping 
               amazon ma csv file data store thay che atle easy joy sake k kaya product ni best selling che am. and csv file ne easy read and write kari sakhavi in pandas ma.

In [17]:
import pandas as pd

df=pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S

In [26]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [27]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S

In [28]:
#passenger survived

import pandas as pd

df = pd.read_csv("train.csv")

df["Survived"].value_counts()

Survived
# 0    10
# 1     9
# Name: count, dtype: int64

Survived
0    10
1     9
Name: count, dtype: int64

In [29]:

#passenger average age 

import pandas as pd

df = pd.read_csv("train.csv")

df["Age"].mean()

# np.float64(28.0)

np.float64(28.0)

In [30]:
# passenger ticket class

import pandas as pd

df = pd.read_csv("train.csv")

df["Pclass"].value_counts()


# Pclass
# 3    12
# 1     4
# 2     3
# Name: count, dtype: int64

Pclass
3    12
1     4
2     3
Name: count, dtype: int64

In [33]:
#missing values in age 

import pandas as pd

df = pd.read_csv("train.csv")
df[df["Age"].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S

In [36]:
#Missing value remove 

import pandas as pd

df = pd.read_csv("train.csv")
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S